Pin python version to 3.9
With 3.10+, telethon requires us to explicitly create an event loop,
otherwise causing the exception

> RuntimeError: There is no current event loop in thread 'MainThread'.
> <sys>:0: RuntimeWarning: coroutine 'AuthMethods._start' was never awaited